#!/usr/bin/env python3
"""Merge mnemonic notes into quizlet.json. Idempotent: skips IDs that already have a note."""
import json
from pathlib import Path

NOTES = {
    1: "Top 4 nguyên tắc phổ biến nhất framework: Fairness, Accountability, Transparency, Privacy. Trong list chỉ có Transparency/explainability → D.",
    2: "KPI dashboard data-driven = phải đo model: accuracy/cost (B) + training time (C). EBITDA/cashflow là KPI tài chính, không phải data system.",
    3: "Refresh policy = bắt kịp emergent risks và ethical posture mới của sản phẩm → B. Còn lại đều là lý do hời hợt/political.",
    4: "ISO 27000 mạnh ở: certification chính thức (A) + recognition quốc tế (D). KHÔNG có legal enforcement (B sai) và KHÔNG technology-specific (C sai).",
    5: "Ethical risk review nên ở Conception (A) — càng sớm càng rẻ. Càng về Deployment càng tốn kém để fix.",
    6: "Social media: nói thật + up front (D) + present face of org (B). Communicate-as-needed = giấu giếm; chỉ focus positive = ethics washing.",
    7: "Ethical culture → nhân viên thấy responsibility & loyalty (B). 3 đáp án còn lại đều mô tả hệ quả gián tiếp/sai bản chất.",
    8: "Privacy by Design 2 cốt lõi: lifecycle-wide protection (A) + Proactive not Reactive (D). Hai trong 7 nguyên tắc gốc của Ann Cavoukian.",
    9: "Categorize risk = dễ identify/manage (A) + hiểu complexity riêng (B). KHÔNG phải để ra universal tactic (C sai vì mỗi loại risk khác nhau).",
    10: "Data như oil vì: monetarily valuable (A) + fuel cho algorithms (D). 'Damage env' và 'monopolized' là claims khác, không phải lý do core.",
    11: "Overfitting = học thuộc training set, KHÔNG generalize cho population → fairness risk = C. Noise/complex là root cause của overfit, không phải lý do fairness.",
    12: "Ethical framework = biến meta-ethics thành actionable steps cụ thể → D. A nhầm chiều, B là regulation, C là phủ định framework.",
    13: "User control thật = granular control (C) + opt-in/opt-out (D). Format storage và gender-of-user không phải choice cho user.",
    14: "Operationalize policy = concrete examples (C) — ngôn ngữ jargon (B) hay annual report (A) không xuống đến hành động hằng ngày.",
    15: "Personhood quyết định cách entity được treat (A). Không phải narrow AI, không phải legal protection cho AI, không phải freedom.",
    16: "Building philosophy = phải anticipate future implications (B). Copy người khác (A), chỉ internal stakeholder (C), 'putting into practice' (D) là execution.",
    17: "Penetration test ROE quy định: targets nào (A) + methods nào hợp lệ (D). Password policy / CCTV không thuộc ROE.",
    18: "Finalize policy = phải document assumptions & choices (D) — để audit về sau. Discard issues / copy peer / test khi đã deploy đều sai.",
    19: "Marketing persona = nhân vật ảo dựa trên demographics/habits/interests (A). Khác brand personality (B), khác marketer thực (C).",
    20: "Beijing AI Principles (D) nhấn mạnh R&D. G20 = governance, Montreal = responsible dev, AMA = augmented intelligence.",
    21: "Moral reasoning bị emotion chi phối (D) — đó là lý do thực tế. Không phải vì thiếu giáo dục (A) hay quá phức tạp (B).",
    22: "AI trong DRP = dùng data-driven techniques để inform strategy (C). Deep learning để 'defense disaster' và NLP fix typo là dùng sai chỗ.",
    23: "Applied ethics = professional ethics (A). Moral relativism, virtue ethics, pluralism là normative/meta-ethics theory.",
    24: "Outliers = data ngoài normal distribution (D). Errors là sai sót, noise là biến động ngẫu nhiên, overfitting là model issue.",
    25: "Press release = concise (A) + digital format (B). Single platform / non-interactive là đặc tính sai.",
    26: "Confirmation bias social: cản trở socio-political cooperation (B) + groupthink (D). KHÔNG dẫn đến diverse friends.",
    27: "Extrajudicial = ruling/scoring NGOÀI tòa án (A). Algorithmic scoring credit/recidivism là ví dụ kinh điển.",
    28: "Pilot CoE problematic khi mục đích = 'demonstrate seriousness' (A) — đó là PR, không phải value thật. B/C/D đều có giá trị thật.",
    29: "COPPA = Children's Online Privacy = bảo vệ trẻ DƯỚI 13 tuổi (B). Đừng nhầm 18.",
    30: "Holding statement = pre-write trước khi cần (A). Để sẵn sàng phản hồi nhanh, KHÔNG phải để cấm ai nói.",
    31: "Policy adherence = unambiguous procedures gắn với clauses (A). Flexibility (B) = dễ lách, legalese (C) = khó hiểu, develop procedure trước (D) = ngược chiều.",
    32: "Categorical imperative (Kant) = universal law (A) + reason để will moral law (C) + treat as end, not means (D). B là consequentialism, không phải Kant.",
    33: "Explainability quan trọng vì nó cung cấp accountability + trust (B). A/C/D mô tả hậu quả nhỏ hơn.",
    34: "Thiếu ethical culture → cognitive dissonance (A) — nhân viên kẹt giữa giá trị cá nhân và yêu cầu công ty.",
    35: "Baseline behavior giúp: track deviance (C) + rollback restore (D). KHÔNG để hold accountable hay optimize cost.",
    36: "Utilitarianism (B) = maximize happiness = nguyên tắc 'right or wrong'. Categorical imperative = duty, deontology = rule, virtue = character.",
    37: "Predeterminism = TẤT CẢ events past/present/future đã được định trước (A). B là mềm hơn (compatibilism), D là religious determinism.",
    38: "Closed source transparency risk = independent auditor không truy cập được (D). Obfuscated code chỉ là kỹ thuật, không phải risk core.",
    39: "Ethics Board = duy trì values-based intent + tăng transparency cách dùng data-driven tech (C). KHÔNG về profit margin.",
    40: "Bridge collapse rất hiếm (imbalanced) + hậu quả nặng → cần Recall (A) để bắt được mọi case dương tính. Accuracy bị skew bởi class âm.",
    41: "AI Fairness 360 (IBM) = open source library đánh giá bias + đề xuất mitigation (D). Không phải 'completely fair model'.",
    42: "Code of ethics có 2 lý do CORE: compels integrity (A) + tạo consistency thay vì patchy (D). 'Prevent regulatory scrutiny' (B) là sai mục đích.",
    43: "Automation bias (A) = tin máy hơn người. Confirmation = tin theo niềm tin có sẵn, complacency = lơ là, implicit = bias ngầm.",
    44: "Self-learning model risk = đưa data mới mà ta không biết (B) → tăng nguy cơ ngầm. Black box (C) đúng cho deep learning, nhưng câu này hỏi self-learning cụ thể.",
    45: "Utilitarianism (B) = greatest good for greatest number. Đây là Bentham/Mill kinh điển.",
    46: "Ethical practices như lợi thế chiến lược: hút talent (A) + strategic partnerships (C) + customer trust (E). 'Comply regulations' chỉ là baseline, không phải differentiator.",
    47: "Performance ↑ thường = model phức tạp hơn → khó explain (C). Đánh đổi accuracy ↔ interpretability kinh điển.",
    48: "California → CCPA cho phép xóa data. (Câu có lỗi đáp án: option C ghi COPPA nhưng câu đúng là CCPA — answer = C theo key.)",
    49: "Policy owner = người đứng giữa các stakeholders để draft (D). Không phải để 'prevent change' hay tự viết một mình.",
    50: "Sentiment analysis = đo perception → shape content/delivery dựa trên đó (A). KHÔNG phải để 'làm user positive hơn' (B = manipulative).",
    51: "Open door ≠ employee voice. Open door cho phép nói nhưng không đảm bảo được nghe (D). Voice = follow-up + được tác động thực sự.",
    52: "Media inquiry: ensure message consistent (D). 'Get out quickly' = vội, 'only friendly outlets' = cherry-pick, 'only required by law' = quá kín.",
    53: "Crisis comm program quản lý = public's perception (D). Real-world effects và internal consensus là khía cạnh khác.",
    54: "Trolley problem = chọn 1 trong 2 kịch bản, mỗi cái đều dẫn đến mất mạng (B). Đây là dilemma kinh điển consequentialism.",
    55: "Certification do industry body cấp (A). Certificate = hoàn thành course. Certification có thể bị revoke và không cần accredit.",
    56: "Smart contract = không cần central authority (A) — chạy trên blockchain, tự execute. Không phải về anonymity hay 'effectiveness'.",
    57: "Regulation khác framework: có legal basis cho litigation (A) + có legal enforcement (B). Framework là flexible/voluntary, regulation thì không.",
    58: "AIA Impact Level 2 = moderate impact: health/well-being (B) + rights of individuals (D). Loss of life = level cao hơn, brief delay = level thấp hơn.",
    59: "Ethics by design = tích hợp ethics từ giai đoạn design ban đầu (B). Tương tự privacy by design.",
    60: "Big Tech virtuous cycle: thuật toán cải thiện → user mới → data tốt hơn → thuật toán càng tốt (D). Self-reinforcing loop.",
    61: "Deepfake ethical concern lớn nhất = chiếm dụng likeness và weaponize chống cá nhân (D). A/B/C đều phụ.",
    62: "DEI trong communication = promote organizational culture embracing values (D). Không phải PR reassurance.",
    63: "CSIRT = Cybersecurity Incident Response Team (D). Nhớ acronym → team xử lý sự cố.",
    64: "SIEM pull từ: system event logs (C) + IDS alerts (D). KHÔNG đọc personal email/encrypted data.",
    65: "Opt-out = tự động thu THUYẾT cho đến khi user nói KHÔNG (D). Opt-in thì ngược lại.",
    66: "Fundamental attribution error = hành vi xấu của tôi do hoàn cảnh, của người khác do tính cách (C). Bias nhận thức kinh điển.",
    67: "Risk management 3 task chính: Identification (C) + Analysis (E) + Mitigation (A). Không có 'deployment' hay 'elimination' (vì rủi ro hiếm khi loại bỏ hoàn toàn).",
    68: "Ethics phải áp dụng từ inception → maintenance → decommissioning (C). Toàn vòng đời, không chỉ khi giao hàng hay sau bị chỉ trích.",
    69: "Predict revenue (số liên tục) = Regression (D). Classification cho discrete, clustering cho unsupervised, dim reduction cho features.",
    70: "Beneficence = 'do GOOD' (chủ động). Non-maleficence = 'do NO HARM' (thụ động). Đáp án A.",
    71: "Track ethical violations để tạo transparency cho effort cải thiện policy (D). KHÔNG phải để dissuade scrutiny hay thay refresh.",
    72: "Differential privacy = chia sẻ pattern dataset mà không lộ cá nhân (B). Khác anonymization (chỉ remove ID), khác access control.",
    73: "Homomorphic encryption = thực hiện phép toán TRÊN dữ liệu mã hóa (D). Cho phép compute mà không cần decrypt.",
    74: "Bias học từ family + social group + media (D). Không bẩm sinh, không chỉ từ media.",
    75: "ZKP = chứng minh điều gì đó EXISTS mà không tiết lộ chi tiết (B). Vd: chứng minh tuổi >= 18 mà không lộ DOB.",
    76: "Robot rights chưa quan trọng vì cần sentience trước (B) — robot hiện tại chưa sentient. Câu hỏi mang tính practical, không anthropocentric.",
    77: "Content moderation: quan trọng nhất = chặn disinformation gây hại nhóm dễ tổn thương (A). Không phải về freedom-balance hay incentive.",
    78: "Form thu feedback explainability = unrestricted text box (B) — cho user diễn đạt đầy đủ. Yes/no và dropdown quá hạn chế.",
    79: "Code of ethics KHÔNG áp dụng cho data subjects (B) — họ là đối tượng được bảo vệ, không phải actor tuân thủ.",
    80: "Negotiate data ethically: xin consent (A) + nói rõ intention (C). Money/incentive = manipulation, dùng giá trị tiền = không phù hợp.",
    81: "HR (Human Resources) = nguồn lực hàng đầu để xây ethical culture (B) — vì culture là về con người.",
    82: "Race/religion là protected class vì historic wholesale discrimination (A). Không phải vì 'identify someone' hay 'collect bị cấm'.",
    83: "Hạn chế adoption CoE: thiếu clarity (B) + thiếu awareness/where-to-apply (C). Comprehensive coverage là tốt, không phải nguyên nhân hạn chế.",
    84: "Data minimization: chỉ collect strictly necessary (B) + chỉ giữ lâu cần thiết (D). Nguyên tắc 'less is more'.",
    85: "Crisis không trung thực → reputational damage (A) — niềm tin mất là khó cứu nhất.",
    86: "Anonymization/pseudonymization yếu vì có thể combine với public data để re-identify (D). Vd Netflix Prize, AOL search.",
    87: "Quality control issues = Vulnerability audit (C). BIA dự phòng business interrupt, BCP cho continuity, lessons learned post-incident.",
    88: "Statement đầu tiên trong crisis = SET TONE cho những gì sẽ theo sau (D). Không phải dump details hay nhận lỗi vội.",
    89: "Shadow ban = vẫn post được nhưng KHÔNG ai phản hồi (D) — silent suppression. Khác ban công khai có notification.",
    90: "Third-party data product: data annotation tools (A) + compiled models (B). Management oversight và lifecycle là internal process.",
    91: "Compliance benefit: tiết kiệm fines dài hạn (A) + tránh reputational damage (D). KHÔNG phải reduce time/cost (đó là illusion).",
    92: "AI labor impact lý do quan trọng nhất = vi phạm labor + human rights (B). Productivity và HITL là phụ.",
    93: "Change management = approaches giúp organization thay đổi (D). Không chỉ về 'ethical culture' (A) mà tổng quát hơn.",
    94: "PII rõ ràng: phone (A) + passport number (D). Device ID/cookie là quasi-identifier (cần combine).",
    95: "FAIR = Findable, Accessible, Interoperable, Reusable (D). Open data principle nổi tiếng.",
    96: "Ethics Board duties = ALL: develop resources + respond to changes + build knowledge repo (C). All-of-the-above.",
    97: "Media plan tools: video briefing (B) + press release (C). Mission statement là internal, public ed campaign là different goal.",
    98: "Transport encryption: SSH (A) + SSH/TLS (B). FTP và HTTP plain text, không encrypt.",
    99: "Ethical culture cần systemic approach + incentive (A). Compliance-only board chỉ chạy theo luật, không tạo culture.",
    100: "Alibi tool dùng Anchor Explanations (A) — subset features cho cùng prediction. Khác SHAP (Shapley) và LIME.",
}

NOTES.update({
    101: "Explainability = giải thích cho NON-EXPERT (A). Interpretability = expert hiểu, auditability = audit được, useability = dùng được.",
    102: "Words 'likely/unlikely/rare' và 'low/medium/high' = qualitative (a) + semi-quantitative (b). Quantitative dùng số chính xác.",
    103: "Employee voice (B) = follow-up cho thấy thay đổi đã thực thi từ feedback. Open door chỉ mở cửa nói, không đảm bảo thay đổi.",
    104: "BIA cần phỏng vấn ground-level vì họ có institutional knowledge nhiều hơn manager (A) — họ làm việc trực tiếp.",
    105: "Comm policy với stakeholder = simple-to-follow examples (A). Dense procedural / flexible verbiage / daily comm đều sai chiều.",
    107: "Prescriptive analysis = phân tích để KÊ TOA hành động (mua doanh nghiệp nào) (C). Predictive = dự đoán, descriptive = mô tả.",
    108: "Resolve business pressure: manage expectations (A) + engage multiple stakeholders (D). KHÔNG hứa 'everyone gets what they want'.",
    109: "Dual-use data = collect cho 1 app, áp dụng cho domain KHÁC (C). Vd data fitness dùng cho insurance.",
    110: "Smart toys: trẻ em dễ bị manipulate hơn → cần extra protection (A). Đó là lý do cốt lõi, khác B/C/D.",
    111: "Normal distribution: mean = median = mode (D). Đối xứng quanh trung tâm.",
    112: "Narrow AI vì: chỉ làm task cụ thể (A) + không xử được tình huống ngoài training (B). Hand-coding (C) không phải đặc trưng narrow.",
    113: "LIME vs SHAP: LIME nhanh hơn (A) nhưng kém chính xác hơn (B). Trade-off speed/accuracy.",
    114: "Cost function cho linear regression: MSE (B) + RMSE (C). Accuracy/recall là cho classification.",
    115: "Suspicion = sợ vì công nghệ chưa biết (C) — root cause của resistance. A/B/D là hệ quả.",
    116: "Crisis low likelihood thường có HIGH impact (A) — chính vì hiếm nên khi xảy ra thì lớn (black swan).",
    117: "Capability caution = ta KHÔNG biết hết AI có thể làm gì → cần kế hoạch (B). Asilomar AI Principles.",
    118: "Professional responsibility ví dụ kinh điển = AMA định nghĩa AI là 'Augmented Intelligence' (B) — đặt người ở trung tâm.",
    119: "Comm risk pitfall: disjointed message (A) + không chú ý flow (C). Follow-up và coordinate giữa department là TỐT.",
    120: "Training data inadequacy phải nói: missing values + cách handle (B) + known bias (D). Time/size không phải bias risk.",
    121: "Focus group > survey vì deeper engagement với community (A). Survey scale tốt hơn nhưng nông.",
    122: "Medical imaging AI: ưu tiên Explainability (A) — bác sĩ phải hiểu vì sao model nói thế trước khi điều trị.",
    123: "Apply security patch = Control (C) trên attack tree. Threat = mối đe dọa, vector = đường tấn công, controller = người điều khiển.",
    124: "Asilomar capability caution: KHÔNG strong assumption về upper limit AI (D) — vì chưa có consensus.",
    125: "Ethics training hiệu quả = ALL: simple + interactive + short-focused (D). Combo cả ba.",
    126: "Radioactive data tracing không impact performance (A) — đó là ưu thế chính so với techniques cũ làm lệch input.",
    127: "Open data principle = FAIR (D). ISO 27001/27017 là security, FATE là Fairness/Accountability/Transparency/Ethics framework khác.",
    128: "Illusory correlation = giả định cause-effect vì 2 biến correlate (D). 'Correlation ≠ causation' bias.",
    129: "Spam evasion = attacker fools system thinking benign (A). Poisoning = đầu độc training data, evasion = đánh ở inference time.",
    130: "Spyware (B) = monitor user behavior bí mật. Virus = lây lan, ransomware = đòi tiền chuộc, trojan = giả dạng.",
    131: "Linear regression dùng cost function (B) — RMSE/MSE. ROC/accuracy là classification.",
    132: "NIST cung cấp Reference materials (C) — chuẩn đo lường. Không bán security tools hay configs.",
    133: "Privacy in AI thường gắn với Data Protection (A) — bảo vệ data cá nhân.",
    135: "Scatter plot positive correlation mạnh = B (strong positive). Cần nhìn slope rõ và scatter chặt.",
    136: "Kali Linux (D) = distro với hundreds of security tools. Wireshark/Nmap/Zenmap là single tools.",
    137: "External stakeholder communicate khi: enhance accuracy update (C) + recall defect (D). Internal change management không cần báo external.",
    138: "White team (B) oversee pentest và ROE adherence. Red = attacker, Blue = defender, Purple = collaboration.",
    139: "Fair competition ethical benefit = encourage product/service differentiation (C) — đa dạng lựa chọn.",
    140: "Ethical impact assessment = focus PREVENT future problems (A). Khác post-mortem nhìn lại.",
    141: "Corporate hegemony: M&A consolidation (A) + monopoly/cartel (B). Marketing spend và investment đa dạng không phải hegemony.",
    142: "Inalienable rights: inherent in all humans (A) + không thể tước trừ extreme circumstances (B). Không conditional, không từ tradition.",
    143: "Turing test = thinking like a human (D). Dù option C nói 'tricking person', đáp án chính thống là 'thinking like human'.",
    144: "AI dùng probability = model of belief về likelihood (B). Không guarantee 100%, không objective likelihood.",
    145: "Moral agency hệ quả: xác định right/wrong (A) + chịu trách nhiệm hành động (B). KHÔNG yêu cầu acts morally correct.",
    146: "Ambient intelligence = IoT always-on personalize trải nghiệm (B). Khác surveillance đơn thuần.",
    147: "Ethical AI engineer: keep up developments/vulnerabilities (C) + clean/sort/audit data (D). Không xây hardware hay 'write equations'.",
    148: "Emerging tech mạnh vì: automate complex ops (A) + self-improve from data (B). 'Exciting' và 'displace workers' là hệ quả, không phải 'why powerful'.",
    149: "Spokesperson tốt: patient (B) + articulate (D). Defensive/lighthearted về topic serious đều sai.",
    150: "STRIDE/VAST = threat modeling tools (D). KHÔNG phải bias mitigation hay network optimization.",
    151: "Ethically problematic: manipulate/alter interpretation (C) + delete erroneous data (D — vì che giấu evidence). Aggregate/format change là OK.",
    152: "Ethics washing = genuine action bị thay bằng superficial promises (D). 'No attempt' là ethics avoidance, không phải washing.",
    153: "Identify case BEFORE first occurs = Superintelligence (D) — vượt mọi khả năng human. Narrow chỉ làm task hẹp đã biết.",
    154: "HR build culture qua hire dựa trên CULTURE FIT (C). Không chỉ technical/soft/leadership.",
    155: "Streamline + tôn trọng autonomy: không hướng user vào điều họ không muốn (B) + tôn trọng quyền customize (C). Bảo vệ user agency.",
    156: "Social media post hashtag = Unstructured data (A) — text tự do. Structured = bảng, semi = JSON.",
    157: "PII tự thân: home address (D). Customer ID / log event / temperature không identify trực tiếp một người.",
    158: "Transparency 85% (C) — đứng đầu trong frameworks. Câu chú thích sẵn của user.",
    159: "Privacy 50% (B) — chỉ một nửa frameworks coi privacy là core tenet. (transparency: 85%, core: 50%).",
    160: "Report to audience = Standard deviation (C) — đơn vị giống data, dễ hiểu. Variance bị bình phương.",
    161: "AI giới hạn autonomy: weapon system tước decision-making (A) + impact vulnerable group khác biệt (B). C/D là benefit, không phải limit autonomy.",
    162: "Private data root cause = stored insecurely (B) — vd database không encrypt. Leaked online là hậu quả, không phải root cause.",
    163: "Mission/vision endorsement quan trọng nhất = Employees (C) — họ phải sống mission hằng ngày, C-suite chỉ tuyên bố.",
    164: "Forensic analysis: xác định WHAT happened (B) + WHO/WHAT responsible (C). Inform stakeholder và mitigate là task khác.",
    165: "Repeat analysis on new data monthly = Pipeline (D). Workflow chung chung, use case là kịch bản, swimlane là diagram.",
    166: "SIEM = Security Information and Event Management (D). Nhớ acronym → quản lý info & event security.",
    167: "Ethical culture = transparency về company values (D). Top-down chỉ là một chiều, document khô khan, button-up sai chữ.",
    168: "Defined policies: consistency + unification culture (A) + accountability explicit (B). Sales/marketing không phải benefit policy.",
    169: "Update CoE để capture evolving ethical risks của product/service (C) — chính lý do tồn tại của review định kỳ.",
    170: "Phân tích trend 5 năm để decide hire = Wisdom (A). Data → Info → Knowledge → Wisdom hierarchy: hành động dựa trên insight = wisdom.",
    171: "Corporate governance = framework accountability để PREVENT ethical violations (C). Không chỉ để 'showcase' hay 'point to'.",
    172: "Sample bias (D) = data không reflect full environment. Prejudice = thành kiến, observer = ai quan sát ảnh hưởng, exclusion = bỏ sót feature.",
    173: "OECD AI Principles dành cho National governments (C). Đó là tổ chức liên chính phủ.",
    174: "Engage external stakeholder = unearth insights về use case trong target community (B). Demonstrate/shield/validation đều sai mục đích.",
    175: "Government recommendation = Promote international cooperation (C). AI là vấn đề xuyên biên giới.",
    176: "Env concern AI: secondary/indirect/cumulative effect (B) — vd carbon footprint của training. A/C/D nói direct nhưng câu hỏi là 'why important'.",
    177: "Public trust = mất rồi khó lấy lại (A). Đó là lý do bảo vệ trust quý hơn fix sau.",
    178: "Feedback loop ML ví dụ: social site track engagement → algorithm → engagement (C) — loop tự tăng cường. A/B là recommendation đơn giản.",
    179: "K-anonymity = không phân biệt được với ÍT NHẤT K-1 cá nhân khác trong dataset (A). Định nghĩa chuẩn.",
    180: "Intellectual Property thường mâu thuẫn với Transparency/Explainability (D) — vì IP cần secrecy, transparency cần openness.",
    181: "Red team = conduct simulated attacks (A). Blue defend, white officiate.",
    182: "Stakeholder = TẤT CẢ người impact hoặc bị impact bởi org (C). Rộng hơn employee/customer.",
    183: "Cross-correlation: combine datasets có thể harm group qua inference (A). K-anonymity bảo vệ individual nhưng không bảo vệ group.",
    184: "Audit researcher = score weight của input attribute lên output (B) — đo importance. Không phải prevent launch hay debias trực tiếp.",
    185: "Visual contract dễ hiểu = pictures + simple text cho layperson (C). Không phải pictures-only hay greater-detail.",
    186: "Crisis comm team cần: adequate resources (B) + clear roles/responsibilities (C). Không 'tell what they want to hear' hay làm độc lập.",
    187: "Algorithm = recipe máy dùng để solve problem (A). Recipe metaphor đơn giản nhất.",
    188: "Data minimization = chỉ collect đủ cho specific purpose (D). Đó là ràng buộc 'fit-for-purpose'.",
    189: "Anonymized dataset re-identify khi combine với dataset khác (D). Vd Netflix prize + IMDb.",
    190: "Info gathering trước drafting CoE = unearth best practices từ peers (C). Không phải copy nguyên hay reaffirm belief.",
    191: "Communicate ethical risk: multiple formats (B) + real-time (D). Không chỉ on-solicit hay single-voice.",
    192: "Strava = differential privacy bảo vệ individual nhưng harm groups (D) — quân đội bị lộ vị trí căn cứ qua aggregate heatmap.",
    193: "Goodhart's law = optimize 1 metric expense of others (A). 'When measure becomes target, ceases to be good measure'.",
    194: "STEEPV = Social/Tech/Econ/Env/Political/Values — phân tích ngoại cảnh tác động business (D). Strategic external analysis.",
    195: "2019: 80-90% (B) equity-future trades do algorithm. Algorithmic trading dominate.",
    196: "Data đã clean → cần Domain expertise (B) đảm bảo nhìn đúng vấn đề. Domain expert biết feature nào quan trọng.",
    197: "Learning algorithm dùng output cho input kế tiếp (D) — feedback. Basic = 1 input/1 output đơn giản.",
    198: "Culture-building workshop = TÍCH HỢP values vào practice hằng ngày (A). Ethics training = TEACH values.",
    199: "Inflated worthiness score → tạo separate decision threshold cho từng group (A). Đó là approach 'group-aware fairness'.",
    200: "What-If tool tích hợp Google Cloud AI (B). LIME/SHAP/ELI5 là tool độc lập.",
})

NOTES.update({
    201: "Engage stakeholder sớm = demonstrate accountability + transparency (B). Không phải để 'prove fully equipped' hay tránh legal.",
    202: "Comm risk to individual: input vào process (A) + proactive not reactive (C). Đối xử như đối tác, không phải reci pient.",
    203: "Comm risk to society: diverse/inclusive/equitable (A) + culturally sensitive (D). Không 'one-direction' hay 'need-to-know'.",
    204: "Plausible deniability = cá nhân có thể bảo 'tôi trả lời randomized' (B) — coin flip privacy mechanism.",
    205: "Fail comm social impact → disenfranchisement (C) + erosion of rights (D). Đó là social-level harm.",
    206: "Blind attribute model vẫn unfair (A) — vì proxy variable (zip code → race). Bỏ feature không đủ.",
    207: "Predictive model nature = reveal data nó train trên (C). Output reveal training distribution.",
    208: "Availability bias = chỉ tìm attributes trong data có sẵn (C). 'Drunk searching for keys under streetlight'.",
    209: "Culture of appreciation = ALL employees identify người xứng đáng reward (D). Không chỉ top director hay manager.",
    210: "Pandemic contact-tracing ưu tiên: Privacy (A) + Accountability (D). Bias/explainability quan trọng nhưng emergency thì 2 cái này hàng đầu.",
    211: "PIPEDA (Canada) đặc biệt = vẫn phải provide service dù user từ chối data usage (C). Khác GDPR/CCPA.",
    212: "Cognitive bias tồn tại vì ta nhận quá nhiều info bị overload (B) — bias = mental shortcut tiết kiệm bandwidth.",
    213: "VR press conference = interactive without co-located (A) — geographic distributed.",
    214: "Ethics board = ethics washing nếu không có power thay đổi (A) — chỉ là cảnh decoration.",
    215: "Cross-correlation: discover info qua inference (A) + compare data points/sets (D). Đối chiếu để tìm pattern.",
    216: "Optimist view of general AI = AI như utility (C) — công cụ hữu ích cho mọi người.",
    217: "Decision involving human life = cần moral code reasoning + priorities (D). Không chỉ programmed reflex.",
    218: "K-anonymity weak với multiple datasets (B) — combine để re-identify. Đó là limit chính.",
    219: "Org culture = 'this is how things are done here' (B). Implicit norm, không phải mandate.",
    220: "Integrity cybersecurity = data không bị modify NGOÀI authorization (A). Khác confidentiality và availability.",
    221: "Pareto curve ML = error rate vs rejection rate (D). Trade-off rõ trong abstain models.",
    222: "Diverse stakeholder cho perspectives → identify risk tốt hơn (A). Group think là kẻ thù của risk identification.",
    223: "'Obligation to shareholders' → AI như tool kinh doanh, accelerate research như online ad (D). View instrumentalist.",
    224: "Moral relativism đối lập với Evidence-based policy (B) — relativism nói không có truth khách quan, evidence-based dựa trên fact.",
    225: "Ethical AI safeguard: transparency/explainability + privacy balance (C) + accountability + bias management (D). 2 trụ cột chính.",
    226: "Learning algorithm cần lots of data → store identifying info user (B) — đó là dilemma fundamental.",
    227: "Group outcome cải thiện qua explainable recommend = dùng game theory (D). Modify behavior bằng strategic info.",
    228: "Pareto efficiency (D) = không thể cải thiện 1 người mà không hại người khác. State 'optimal' kinh điển.",
    229: "Ethical predictive model: accurate + fair + explainable (A). Trio kinh điển.",
    230: "Deployment phase = dùng model ở real-life, monitor error rate + accuracy (A). Khác training (validate) và development.",
    231: "60/20/20 split = optimized training set (D) — train/validate/test. Classic ML split.",
    232: "Algorithm thử 10 sorting → dùng best fit = Learning algorithm (B). Tự cải thiện dựa trên data.",
    233: "Crime model bias từ dataset historical: drug arrest cao → correlate area = high crime (B). Bias data → bias output.",
    234: "Counter adversarial = limit precise outputs (C) — output mơ hồ thì attacker khó suy luận model.",
    235: "Glass-box model + skewing attribute → re-run without it (D). Explainability cho phép intervene.",
    236: "Media campaign factors: environment launch (B) + time-sensitive nature (D). Bottom-line/risks là khía cạnh khác.",
    237: "GDPR data 'adequate, relevant, NOT EXCESSIVE' (C) — đó là chính xác text article 5(1)(c).",
    238: "Leptokurtic (C) = kurtosis cao = tail dày = nhiều outlier. Mesokurtic = normal, platykurtic = ít outlier.",
    239: "ML dataset security = sound data governance (A). Foundation cho mọi practice khác.",
    240: "Black box problem = model deploy nhưng researcher không biết tại sao decision (A). Definition kinh điển.",
    241: "Explainable algorithm trong recommend trả lời câu 'WHY?' (C) — vì sao gợi ý cái này.",
    242: "Ethical model = accurate + explainable + fair (C). Khác câu 229 về privacy chỗ khác.",
    243: "Weather app learning algo → collect location mỗi lần mở (C) — privacy creep, biết user ở đâu.",
    244: "Disparate impact (A) = outcome khác nhau giữa groups dù không có ý định phân biệt. Treatment = ý định, impact = kết quả.",
    245: "Lower decision threshold 40% → tạo more mistakes nhưng có thể fairer-less-accurate (A). Trade-off classic.",
    246: "Sort low-to-high logical: scan smallest, set index 0, remove, repeat increment index (D). D có đủ steps + repeat.",
    247: "What-if scenario = think về MISTAKES → identify gì cần làm sau ethical violation (B). Theo answer key (dù option C nghe hợp lý hơn).",
    248: "Comm transparency = Clear, concise, coherent (A) — 3C. Complex/contained là ngược lại.",
    249: "Reverse-engineer double coin flip differential = 75% truthful 'yes/no' (D). 50% trả lời thật + 25% (50% × 50%) lucky lie = đúng.",
    250: "Predictive model bank ACCURATE prediction person can't pay → vẫn negative consequence vì gây harm individual (D). Accurate ≠ fair.",
    251: "Local differential privacy (D) = noise add ngay tại user, ngay người collect cũng không thấy raw. Global = trust collector.",
    252: "Adversarial algorithm = purposefully biased để identify unfair attribute (B). Test fairness bằng cách 'attack'.",
    253: "RACI = Responsible, Accountable, Consulted, Informed (D). Project mgmt framework chuẩn.",
    254: "Hedge fund predictive model = predict stock movement, exploit market both directions (D). High-frequency trading.",
    255: "Self-fulfilling prediction (B) = model validate bởi chính ảnh hưởng nó tạo ra. Vd predictive policing → tăng patrol → tăng arrest → confirm prediction.",
    256: "Fairness ML group level vẫn harm individuals trong group đó (B). Aggregate fair ≠ individual fair.",
    257: "Digital security trust prerequisite: Authentication (C) + Authorization (A). Auth-N (who) + Auth-Z (what allowed).",
    258: "Beneficence (D) = promote well-being không chỉ moral agent mà cả animals/env/societies. Rộng nhất.",
    259: "False negative = predicted negative, actual positive (B). 'Miss' the positive case.",
    260: "Risk comm regulatory obligation = Compliance audit (D). Ethics review/PR/BIA mục đích khác.",
    261: "Predictive model insight không đổi nếu individual data có/không (A) — đó là differential privacy guarantee.",
    262: "Public dataset privacy risk: Google Maps satellite (C) — có thể identify nhà/căn cứ qua image.",
    263: "Word2Vec advantage over black box = ta access training data (A) — biết source bias.",
    264: "Self-driving car cần Robustness to adversarial examples (A) — không bị fool bởi sticker trên biển báo.",
    265: "Normal distribution histogram = Bell shape (C) — đường cong chuông Gauss.",
    266: "Cross-validation: validation set tune performance (C). Training fit, test final, validation tune.",
    267: "Liability proactive vì law lags innovation (A) — tech đi trước, luật chạy theo.",
    268: "Audit document: purpose/agenda KHÔNG phải step quan trọng (theo answer key). Specify what audited (C) + procedures (D) là core.",
    269: "IP misuse = dùng IP để tránh transparency (C) — 'trade secret' để che bias. Patent (A) là OK.",
    270: "Mitigate unwillingness feedback = communicate importance of feedback (C). Educate why-it-matters.",
    271: "Complex learning function: hiểu input/output, KHÔNG hiểu algorithm (A). Black box behavior.",
    272: "Learning algo fact: dù bạn không share data trực tiếp, algorithm vẫn đoán đúng từ data liên quan (A). Inference power.",
    273: "Netflix Prize re-identify qua MULTIPLE datasets (D) — combine với IMDB review để de-anonymize.",
    276: "Subgroup protection impractical vì accuracy bị giảm vô lý (B). Càng nhiều subgroup → càng ít data per group → noise.",
    277: "Data minimization = delete unused data EARLY AND OFTEN (A). Càng giữ lâu càng risk.",
    278: "Accountability (B) = stakeholder trách nhiệm tạo & dùng tech. Khác transparency (open) và explainability (understand).",
    279: "Fair competition build user trust trong tech nói chung (B). Choice (C/D) chỉ là một benefit, trust là core.",
    280: "City + State làm 2 input riêng → vi phạm 'No correlating data' (A). Chúng correlate cao, gây collinearity.",
    281: "Cultural reflection in training: model select demographic ÍT vì historical underrepresent (B). Bias do cultural reflection.",
    282: "BIPA biometric: consent (A) + destroy timely (C). Storage location/transmission không phải requirement chính.",
    283: "Accuracy = correct / total predictions (B). Đơn giản nhất.",
    284: "Pseudocode = explainable description cho HUMAN, không cho computer (A). Bridge giữa code & natural language.",
    285: "Unfair model NATURALLY optimize fewest mistakes (C) — accuracy first, fairness sau. Đó là default behavior.",
    286: "Change management → smooth transition (C). Không fast/slow, mà smooth.",
    287: "Reinforcement bias (D) = same data sample đi sample lại, model perspective bị thu hẹp.",
    288: "SSL/TLS/SSH = Encryption protocols (C). Đều secure transport layer.",
    289: "AI uphold justice = design from start cho fairness + minimize bias (B). Không thay thẩm phán.",
    290: "Game theory: outcome best for INDIVIDUAL có thể che lấp outcome best for GROUP (D). Prisoner's dilemma.",
    291: "Black box (A) ưa bởi business vì less competition — IP hidden, đối thủ không sao chép.",
    292: "BIA = predict business interruptions + recovery strategies (A). Scope khác risk acceptance.",
    293: "Dating algorithm bias qua collaborative filtering (C) — recommend dựa trên user tương tự, củng cố pattern existing.",
    294: "Basic vs complex algorithm: basic có set choices, complex tự tìm model (C). Freedom degree khác nhau.",
    295: "Sensitive column (C) = không identifiable nhưng cần protect (vd disease). Quasi-ID để identify, sensitive là content.",
    296: "Feedback ethical crisis = make operational improvements (B). Không phải PR/appease/motivate.",
    297: "Turing test (B) = test thinking like human. Definition kinh điển Alan Turing.",
    298: "Adversarial model dùng PERTURBED inputs (D) — nhiễu nhỏ để observe output thay đổi.",
    299: "Avoid feedback loop ML = label outputs để prevent retrain bias (D). Mark output → không feed lại như fresh data.",
    300: "Automation bias ví dụ: dùng scraped Twitter > survey data (A) — tin máy hơn người gather thủ công.",
})

NOTES.update({
    301: "Explainable AI cooperation giữa algorithm & human depends on TRUST (B). Trust = nền tảng của human-AI collaboration.",
    302: "Transparency từ customer view: simple terms (B) + prompt response questions (D). Không dump white paper hay full security guide.",
    303: "True positive = predicted positive, actual positive (C). 'Hit'.",
    304: "Deep learning algorithm thách thức explainable AI (A) — complexity quá cao, attribute weights khó tách.",
    305: "Risk management fundamental: Mitigation (A) + Identification (D). Auth/compliance là khác task.",
    306: "Inclusive design AI: leverage customer input giảm bias (A) + consider bias as spectrum (B). Solve-many-extend-one là Microsoft IDP nhưng KHÔNG ở best practice list này.",
    307: "Develop phase = train, repeat training tới khi curve tốt hơn (A). Không phải specify type (đó là design).",
    308: "Training phase = adjust model trên SUBSET data, optimize lower error (C). Khác develop và deploy.",
    309: "Black box AI = khó hiểu HOW/WHY system made decision (B). Process opaque, không phải data hay output.",
    310: "Hospital treatment AI = Bioethics (C). Domain medical = bioethics, dù 'engineering ethics' nghe gần.",
    311: "SLA = Service-level agreement (B) — establish goals + cách đạt. SaaS = delivery model, ToS/EULA = legal terms.",
    312: "Unknown Unknowns = thiếu explainability, không biết model thật sự nhìn gì (C). Donald Rumsfeld concept.",
    313: "Statistical parity (B) fail merit dù maintain accuracy — bằng nhau output nhưng bỏ qua merit. Trade-off fairness.",
    314: "IEEE 7000 series: machine-readable privacy terms (A) + emulated empathy (C). Không phải fair competition/safety.",
    315: "ML cần human EXTRACT feature (C). DL tự extract feature qua neural net layers.",
    316: "Empirical reflection: model image không phân biệt photo of dog vs photo of photo (C). Empirical limit.",
    317: "Error function = % predictions không match actual (D). Đo wrong rate để optimize.",
    318: "Marketplace ML bias từ short feedback cycles (D) — dating app: swipe nhanh → bias tăng nhanh.",
    319: "Fair model: minimize error rate AS LONG AS parity obtained (D). Fairness gắn với parity, accuracy là hệ quả.",
    320: "Fairness = just treatment KHÔNG có favoritism hay discrimination (C). Definition kinh điển.",
    321: "Black box fairness tool: change inputs, evaluate outputs (D). Không thấy training data, chỉ test perturbation.",
    322: "Human rights khi build AI = Fairness/non-discrimination (A) — primary reason consider human rights.",
    323: "No Free Lunch theorem (D): all models same error averaged over all distributions. Không model nào universal best.",
    324: "Accountability governance = ALL employees feel responsible build trustworthy systems (A). Distributed responsibility.",
    325: "Cognitive bias: gặp gap context → fill with existing knowledge (A). Brain auto-fill blank.",
    326: "Auditing model = post-processing bias mitigation (C) — audit sau khi predict. Pre-process data, in-process algorithm.",
    327: "Equality of false negatives (B) = equalize số mistakes per subgroup. 'Equal opportunity' fairness metric.",
    328: "Combat implicit bias 3: aware own biases (B) + diverse interactions (D) + counter-stereotypical examples (A). Surround similar/single-source là củng cố bias.",
    329: "Explainable adjustable algo limit = users tend make SELFISH decisions (A) — khi thấy weight, tối ưu cho mình.",
    330: "Pessimist general AI = potential extinction event (B). Existential risk Bostrom/Yudkowsky.",
    331: "Coin flip privacy: heads=true answer, tails=random (C). Plausible deniability + still useful aggregate.",
    332: "Ethical data integrity: holders trustworthy (A) + gathered ethically (B). Type/value là khía cạnh khác.",
    333: "Non-maleficence = principle of DO NO HARM (A). Ngược nghĩa với beneficence (do good).",
    334: "Common ethical framework KHÔNG thường xét = Security (C). Privacy/transparency/humanity thường có.",
    335: "Leadership champion = decide based on COMPANY VALUES dù adversity (A). Không personal opinion/popularity/brand.",
    336: "Explainable model benefit = recruiting leverage (A) — talent thích công ty transparent.",
    337: "Tickets chia đều giữa groups = Statistical parity (C) — equal proportion output. Equal split = parity case.",
    338: "AI black box = challenge hiểu inner working opaque system (C). Definition tổng quát.",
    339: "AMA: 'A' nên là Augmented (B) — augmented intelligence, không phải artificial. Hỗ trợ bác sĩ, không thay.",
    340: "SIEM purpose = aggregate alerts từ disparate sources vào 1 platform analysis (C). Centralize security telemetry.",
    341: "Pilot ethical benefit: minimize impact ethical issue (B) + reveal accountability/auditability gaps (D). Không phải để satisfy investor.",
    342: "Differential privacy adds NOISE (C) — random noise vào dataset/output để bảo vệ individual.",
    343: "Criminal justice risk assessment KHÔNG race-neutral vì data reflect historical bias (A) — vd ProPublica COMPAS analysis.",
    344: "Perverse instantiation (C) = AGI hiểu broad goal theo cách bất ngờ negative. Bostrom paperclip maximizer.",
    345: "AI performance ↑ → model complexity ↑ → khó explain (B). Cùng motif như Q47.",
    346: "Equality on outputs = error rate parity (A) — bằng error rate giữa groups.",
    347: "Hospital treatment AI = Bioethics (A). Câu lặp Q310, đáp án A vì options đảo lại.",
    348: "Model self-clean impartial = list bias + domain tests để adjust (B). Không chỉ compute power hay data lượng.",
    349: "Identify ethical concern CoE 3: stakeholder feedback (B) + research peer mistakes (C) + prior issues your product (D). Govt regulation chỉ baseline.",
})


def main():
    path = Path(__file__).parent / "quizlet.json"
    data = json.loads(path.read_text())
    added = 0
    skipped = 0
    missing_in_dict = []
    for q in data:
        qid = q["id"]
        existing = q.get("note", "")
        # Preserve user-authored notes (style: starts with '('), overwrite generated ones
        is_user_note = existing.startswith("(")
        if is_user_note:
            skipped += 1
            continue
        if qid in NOTES:
            q["note"] = NOTES[qid]
            added += 1
        else:
            missing_in_dict.append(qid)
    # Reorder keys so note sits next to answer
    out = []
    for q in data:
        ordered = {"id": q["id"], "question": q["question"], "options": q["options"], "answer": q["answer"]}
        if q.get("note"):
            ordered["note"] = q["note"]
        out.append(ordered)
    path.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"Added: {added}")
    print(f"Skipped (already had note): {skipped}")
    print(f"Total questions: {len(data)}")
    print(f"With note: {sum(1 for q in out if q.get('note'))}")
    if missing_in_dict:
        print(f"Missing in NOTES dict: {missing_in_dict}")


if __name__ == "__main__":
    main()
